### ISSUE TITLE
ADR: Satellite Robot Credential Refresh via Heartbeat-Driven Flow

### ISSUE THREAD

**Issue by bupd** [container-registry/harbor-satellite#307]
## Status

Proposed

## Context

Ground Control creates a Harbor robot account per satellite during registration (ZTR). Harbor robot secrets expire after a configurable duration (default: 30 days). When expired, the satellite loses the ability to pull state artifacts from Harbor (gets 401 on `/v2/`), and currently has no mechanism to obtain fresh credentials.

Since satellites are the only party that can initiate communication (GC cannot contact satellites), the refresh flow must be satellite-initiated.

Additionally, `robot_accounts.robot_secret` is currently stored in plaintext in GC's database. This should be replaced with a one-way argon2id hash for security.

## Decision

Implement a heartbeat-driven credential refresh flow with a new `POST /satellites/refresh-credentials` endpoint on Ground Control. Store an argon2id hash of `robotName+secret` instead of the plaintext secret.

##	Note 
>  i would probably not do it after the state replication is failed and the error happened but before that by.

(robot-account-expiry-pendingms - next-state-replication x 2) <= 0 ->  trigger action "refresh_credentials"

### Credential Refresh Flow

```mermaid
sequenceDiagram
    participant S as Satellite
    participant GC as Ground Control
    participant H as Harbor

    Note over S: State replication fails with 401

    S->>GC: POST /satellites/sync<br/>(heartbeat + error: credentials_invalid)
    GC->>H: GET /api/v2.0/robots/{id}<br/>(check expires_at)
    H-->>GC: { expires_at: <past_timestamp> }
    Note over GC: confirms robot is expired
    GC-->>S: 200 { action: "refresh_credentials" }

    S->>GC: POST /satellites/refresh-credentials<br/>(robot_name + secret)
    Note over GC: auth.VerifyPassword(<br/>robot_name + secret,<br/>stored_hash)

    GC->>H: PUT /api/v2.0/robots/{id}<br/>{ duration: 30 }
    H-->>GC: 200 (expiry extended)

    GC->>H: PATCH /api/v2.0/robots/{id}<br/>(RefreshSec - rotate secret)
    H-->>GC: 200 { secret: "new_secret" }

    Note over GC: stores argon2id(robot_name + new_secret)
    GC-->>S: 200 { username, secret }
    Note over S: updates local config via hot-reload
```

### Satellite-Side Decision Flow

```mermaid
flowchart TD
    A[State Replication Attempt] --> B{Auth Success?}
    B -->|200| C[Replicate Artifacts]
    B -->|401| D[Set credentials_invalid flag]
    D --> E[Next Heartbeat to GC]
    E --> F{Response has action?}
    F -->|refresh_credentials| G[POST /satellites/refresh-credentials]
    F -->|none| H[Retry on next heartbeat]
    G --> I{New creds received?}
    I -->|Yes| J[Update StateConfig via hot-reload]
    I -->|No| H
    J --> A
```

### GC-Side Verification Flow

```mermaid
flowchart TD
    A[POST /satellites/refresh-credentials] --> B{Auth Method?}
    B -->|SPIFFE| C[Extract SPIFFE ID from mTLS]
    B -->|ZTR| D[Receive robot_name + secret]
    C --> E[Map SPIFFE ID to satellite record]
    D --> F[argon2id verify robot_name+secret<br/>against stored hash]
    F --> G{Hash matches?}
    G -->|No| H[401 Unauthorized]
    G -->|Yes| I[Look up robot_id for satellite]
    E --> I
    I --> J[PUT /robots/id - extend duration]
    J --> K[PATCH /robots/id - RefreshSec]
    K --> L[Store argon2id hash of new creds]
    L --> M[Return new username + secret]
```

### Steps

1. **Satellite detects auth failure**: When state replication fails with 401, satellite includes `credentials_invalid` error in its next heartbeat (`POST /satellites/sync`).

2. **GC checks robot expiry**: On receiving the error, GC calls `GET /api/v2.0/robots/{id}` to check `expires_at`. If `current_time > expires_at`, robot is expired.

3. **GC responds with refresh action**: Includes `action: "refresh_credentials"` in the heartbeat response.

4. **Satellite calls refresh endpoint**: `POST /satellites/refresh-credentials` with `robot_name + secret`.

5. **GC verifies satellite identity**: Computes `argon2id(robot_name + secret)` and compares against stored hash using `auth.VerifyPassword`. This works even when the robot is expired in Harbor since verification is local to GC.

6. **GC renews the robot in Harbor**:
   - `PUT /api/v2.0/robots/{id}` with new `duration` to extend `expires_at`
   - `PATCH /api/v2.0/robots/{id}` (RefreshSec) to generate a new secret

7. **GC returns new credentials and stores new hash**: Returns new `username + secret` to satellite. Stores `argon2id(robot_name + new_secret)` in DB.

8. **Satellite updates local config** with new credentials via hot-reload.

### Authentication for Refresh Endpoint

- **SPIFFE mode**: Satellite authenticates via mTLS. GC extracts SPIFFE ID and maps it to the satellite record.
- **Non-SPIFFE mode (ZTR)**: Satellite sends `robot_name + secret`. GC verifies via `auth.VerifyPassword(robot_name + secret, stored_hash)`. This is the only way to verify satellite identity in non-SPIFFE mode.

### Hashed Secret Storage

Replace plaintext `robot_secret` with argon2id hash. Reuse the existing `auth.HashPassword` / `auth.VerifyPassword` from `ground-control/internal/auth/password.go` (OWASP 2024 recommended argon2id params, same as GC admin password hashing).

```go
// During ZTR (store hash)
hash, _ := auth.HashPassword(robotName + secret)

// During refresh (verify)
valid, _ := auth.VerifyPassword(robotName + sentSecret, storedHash)
```

## POC Validation

Tested against `demo.goharbor.io` (Harbor v2.14.0).

### Test Setup

Two robot accounts used:
- `robot_testing` (id: 3432319) - created Jan 15 2026, duration: 1 day, expired Jan 16 2026
- `robot_catalog` (id: 3446282) - created Feb 6 2026, duration: 1 day, active

### Test 1: Expired Robot Returns 401

```
curl -u "robot_testing:Harbor12345" "https://demo.goharbor.io/v2/"
-> HTTP 401
```

### Test 2: Expiry Detectable via Admin API

```
GET /api/v2.0/robots/3432319
{
  "expires_at": 1768574010,   // Jan 16 2026 (expired)
  "duration": 1
}
```

`expires_at` is a Unix timestamp. `time.Now().Unix() > expires_at` means expired.

### Test 3: Cannot Verify Secret When Expired

Both correct and incorrect secrets produce identical results on an expired robot:

| Endpoint | Correct Secret | Wrong Secret |
|---|---|---|
| `/v2/` | 401 UNAUTHORIZED | 401 UNAUTHORIZED |
| Token service | 200, empty actions | 200, empty actions |

Harbor cannot distinguish valid vs invalid secrets for expired robots. This confirms that local hash verification (argon2id) is required for the refresh endpoint.

### Test 4: Expired Robot Fails on Catalog

```
# Added catalog permission to expired robot_testing
curl -u "robot_testing:Harbor12345" "https://demo.goharbor.io/v2/_catalog"
-> HTTP 401: "unauthorized to list catalog"
```

### Test 5: Duration Extension Renews Robot

```
PUT /api/v2.0/robots/3432319
{ "name": "robot_testing", "duration": 30, ... }
-> HTTP 200

GET /api/v2.0/robots/3432319
{
  "expires_at": 1771166010,   // Feb 14 2026 (renewed)
  "duration": 30
}
```

Note: `expires_at` is calculated as `creation_time + duration`. Extending `duration` recalculates `expires_at`.

### Test 6: Robot Works Immediately After Renewal

```
curl -u "robot_testing:Harbor12345" "https://demo.goharbor.io/v2/"
-> HTTP 200

curl -u "robot_testing:Harbor12345" "https://demo.goharbor.io/v2/_catalog"
-> HTTP 200: {"repositories":["jeff-test/testing","oci-test/oci-chart-example",...]}
```

### Test 7: RefreshSec vs UpdateRobot

- `PATCH /api/v2.0/robots/{id}` (RefreshSec): Only rotates the secret. Does NOT extend expiry.
- `PUT /api/v2.0/robots/{id}` (UpdateRobot): Extends duration/expiry. Does NOT change the secret.

Both operations are needed: PUT to renew, PATCH to rotate.

### POC Conclusion

Harbor API supports all operations needed for this flow. `PUT` extends expiry, `PATCH` rotates secret. Robot becomes functional immediately after renewal. Secret cannot be verified when robot is expired, confirming the need for local argon2id hash verification.

### Ground Control Changes

1. **DB Migration**: Replace `robot_secret VARCHAR(255)` with `robot_secret_hash VARCHAR(255)` in `robot_accounts` table. Add `expires_at BIGINT` column to cache robot expiry locally.

2. **Modify ZTR handlers**: After creating robot in Harbor, store `auth.HashPassword(robotName + secret)` instead of plaintext secret.

3. **Modify `syncHandler`** (heartbeat): Parse `credentials_invalid` error from heartbeat payload. Check robot expiry (local `expires_at` or via `GetRobotAccount()`). Include `action: "refresh_credentials"` in response if expired.

4. **Add `POST /satellites/refresh-credentials` route**: Verify satellite identity via `auth.VerifyPassword(robotName + secret, storedHash)` or SPIFFE mTLS. Call `UpdateRobotAccount()` (PUT) to extend duration. Call `RefreshRobotAccount()` (PATCH) to rotate secret. Store new hash, return new credentials.

### Satellite Changes

1. **Detect auth failures**: When state fetcher gets 401, set `credentials_invalid` flag.

2. **Include errors in heartbeat**: Add error field to heartbeat payload sent to `POST /satellites/sync`.

3. **Handle refresh action in heartbeat response**: Parse `action` field. When `refresh_credentials`, call `POST /satellites/refresh-credentials` with current `robot_name + secret`.

4. **Update local config**: On receiving new credentials, update `StateConfig.Auth` and persist via hot-reload.

## Consequences

- Satellites can self-heal from expired credentials without manual intervention
- No changes to the communication model (satellite-initiated only)
- Robot secrets no longer stored in plaintext in GC database (argon2id hash)
- Satellite identity verification works independently of Harbor for non-SPIFFE mode
- Robot expiry duration must be longer than heartbeat interval (otherwise satellite cannot report the error before losing access)
- GC needs admin-level Harbor credentials to update robot accounts (already the case)
- `expires_at` is calculated as `creation_time + duration` in Harbor, so extending duration pushes expiry relative to creation time, not current time

**Comment by bupd** [comment]
PR #310 partially overlaps with this ADR, but it does not fully implement the heartbeat-driven credential refresh flow described here.

What #310 appears to cover:
- Replaces plaintext robot_secret storage with robot_secret_hash.
- Adds robot_expiry tracking in Ground Control.
- Adds ROBOT_DURATION_DAYS for configurable robot duration.
- Refreshes/passes a fresh robot secret during ZTR/SPIFFE ZTR paths.

Still not covered from this issue:
- No POST /satellites/refresh-credentials route is added.
- Heartbeat /satellites/sync does not parse/report credentials_invalid or return action: refresh_credentials.
- Satellite-side 401 detection does not set a credentials_invalid flag for heartbeat.
- Satellite-side heartbeat handling does not call a refresh endpoint or update local credentials from a refresh response.
- The full PUT-to-renew plus PATCH-to-rotate flow for expired robots is not exposed as a satellite-initiated refresh workflow.

Keeping this open because #310 improves secret storage and ZTR refresh behavior, but does not implement the proposed self-healing credential refresh flow.

**Comment by NucleoFusion** [comment]
cc @bupd @Vad1mo 
After spending some time on this ADR, I have some questions
Mainly,

1. Where should I store the validity/invalidity of credentials?
	- I wanted it such that if a request returns 401 or on startup etc, the request sets the `IsCredentialValid` as false. And this state persists till the next heartbeat where we send this to GC. Which eventually returns a new token to satellite, and then I set `IsCredentialValid` as true again.
	- I am currently storing it in the Config in the `StateConfig` but I am not sure about whether this is the best way to do it, since this would mean updating config every invalid/valid toggle.

2. What is the best way to talk to harbor to check validity of credentials, do I just hit any endpoint? or is one endpoint a standard for this kind of practice?
